name: Deploy Storefront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Export static files
        run: npm run export

      - name: Copy build to server (tmp folder)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 54.159.56.126
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "out/*"
          target: "/home/ubuntu/tmp_build"
          strip_components: 1

      - name: Deploy to web root
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 54.159.56.126
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo mv /home/ubuntu/tmp_build/* /var/www/html/
            sudo systemctl restart nginx

